### PR TITLE
Add getter for position

### PR DESCRIPTION
**Pull request by Freyskeyd**
Add a getter to the position.

Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>

### CODE REVIEW

**Comment by Geal** [comment]
Why is it needed?

**Comment by Freyskeyd** [comment]
The `getter` is a useful information to display (I used it in `trace!`)
For the `setter` I don't know, maybe it's completely useless ?

**Comment by Geal** [comment]
The getter can be useful, but the setter would break the behaviour of the
buffer

**Comment by Freyskeyd** [comment]
That's right, I will remove it.

**Comment by Freyskeyd** [comment]
I've a question about how this repository is named. `Circular` but the main struct if `Buffer`. Would keep that way?

**Comment by Geal** [comment]
probably, it's just a crate name

**Pull request merged**
